apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: db:5432
    password: ${DB_PASSWORD}
    user: ${DB_USER}
    database: ${DB_NAME}
    isDefault: false
    jsonData:
      sslmode: disable
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    editable: true
