# Generated by Django 4.2 on 2026-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
