{
 "title": "Docker Containers Monitoring",
 "description": "Docker Containers Monitoring",
 "tags": [
  "docker",
  "containers",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Docker Containers Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_info{container_name=~\"delux_.*\"}"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[5m]) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"} / 1024 / 1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Docker Containers Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"docker\"}"
    }
   ]
  }
 ]
}